/*
 * TrixyAboutBox.java
 *
 * Created on February 25, 2008, 9:49 AM
 */

package kuhnlab.trixy;

import org.jdesktop.application.Action;

/**
 *
 * @author  jrkuhn
 */
public class TrixyAboutBox extends javax.swing.JDialog {
    
    /** Creates new form TrixyAboutBox */
    public TrixyAboutBox(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        layeredPane = new javax.swing.JLayeredPane();
        logo = new javax.swing.JLabel();
        appDescLabel = new javax.swing.JLabel();
        versionLabel = new javax.swing.JLabel();
        appVersionLabel = new javax.swing.JLabel();
        vendorLabel = new javax.swing.JLabel();
        appVendorLabel = new javax.swing.JLabel();
        homePageLabel = new javax.swing.JLabel();
        appHomePageLabel = new javax.swing.JLabel();
        closeButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(null);
        setName("Form"); // NOI18N

        layeredPane.setName("layeredPane"); // NOI18N

        org.jdesktop.application.ResourceMap resourceMap = org.jdesktop.application.Application.getInstance(kuhnlab.trixy.TrixyApp.class).getContext().getResourceMap(TrixyAboutBox.class);
        logo.setIcon(resourceMap.getIcon("logo.icon")); // NOI18N
        logo.setText(resourceMap.getString("logo.text")); // NOI18N
        logo.setAlignmentY(0.0F);
        logo.setName("logo"); // NOI18N
        logo.setBounds(0, 0, 416, 310);
        layeredPane.add(logo, javax.swing.JLayeredPane.DEFAULT_LAYER);

        appDescLabel.setFont(resourceMap.getFont("appDescLabel.font")); // NOI18N
        appDescLabel.setForeground(resourceMap.getColor("appDescLabel.foreground")); // NOI18N
        appDescLabel.setText(resourceMap.getString("appDescLabel.text")); // NOI18N
        appDescLabel.setName("appDescLabel"); // NOI18N
        appDescLabel.setBounds(120, 160, 280, 19);
        layeredPane.add(appDescLabel, javax.swing.JLayeredPane.PALETTE_LAYER);

        versionLabel.setFont(resourceMap.getFont("versionLabel.font")); // NOI18N
        versionLabel.setForeground(resourceMap.getColor("versionLabel.foreground")); // NOI18N
        versionLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        versionLabel.setText(resourceMap.getString("versionLabel.text")); // NOI18N
        versionLabel.setName("versionLabel"); // NOI18N
        versionLabel.setBounds(50, 190, 55, 14);
        layeredPane.add(versionLabel, javax.swing.JLayeredPane.PALETTE_LAYER);

        appVersionLabel.setFont(resourceMap.getFont("appVersionLabel.font")); // NOI18N
        appVersionLabel.setForeground(resourceMap.getColor("appVersionLabel.foreground")); // NOI18N
        appVersionLabel.setText(resourceMap.getString("appVersionLabel.text")); // NOI18N
        appVersionLabel.setName("appVersionLabel"); // NOI18N
        appVersionLabel.setBounds(120, 190, 280, 14);
        layeredPane.add(appVersionLabel, javax.swing.JLayeredPane.PALETTE_LAYER);

        vendorLabel.setFont(resourceMap.getFont("vendorLabel.font")); // NOI18N
        vendorLabel.setForeground(resourceMap.getColor("vendorLabel.foreground")); // NOI18N
        vendorLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        vendorLabel.setText(resourceMap.getString("vendorLabel.text")); // NOI18N
        vendorLabel.setName("vendorLabel"); // NOI18N
        vendorLabel.setBounds(50, 210, 55, 14);
        layeredPane.add(vendorLabel, javax.swing.JLayeredPane.PALETTE_LAYER);

        appVendorLabel.setFont(resourceMap.getFont("appVendorLabel.font")); // NOI18N
        appVendorLabel.setForeground(resourceMap.getColor("appVendorLabel.foreground")); // NOI18N
        appVendorLabel.setText(resourceMap.getString("appVendorLabel.text")); // NOI18N
        appVendorLabel.setName("appVendorLabel"); // NOI18N
        appVendorLabel.setBounds(120, 210, 280, 14);
        layeredPane.add(appVendorLabel, javax.swing.JLayeredPane.PALETTE_LAYER);

        homePageLabel.setFont(resourceMap.getFont("homePageLabel.font")); // NOI18N
        homePageLabel.setForeground(resourceMap.getColor("homePageLabel.foreground")); // NOI18N
        homePageLabel.setText(resourceMap.getString("homePageLabel.text")); // NOI18N
        homePageLabel.setName("homePageLabel"); // NOI18N
        homePageLabel.setBounds(50, 230, 55, 20);
        layeredPane.add(homePageLabel, javax.swing.JLayeredPane.PALETTE_LAYER);

        appHomePageLabel.setFont(resourceMap.getFont("appHomePageLabel.font")); // NOI18N
        appHomePageLabel.setForeground(resourceMap.getColor("appHomePageLabel.foreground")); // NOI18N
        appHomePageLabel.setText(resourceMap.getString("appHomePageLabel.text")); // NOI18N
        appHomePageLabel.setName("appHomePageLabel"); // NOI18N
        appHomePageLabel.setBounds(120, 230, 280, 20);
        layeredPane.add(appHomePageLabel, javax.swing.JLayeredPane.PALETTE_LAYER);

        javax.swing.ActionMap actionMap = org.jdesktop.application.Application.getInstance(kuhnlab.trixy.TrixyApp.class).getContext().getActionMap(TrixyAboutBox.class, this);
        closeButton.setAction(actionMap.get("closeAboutBox")); // NOI18N
        closeButton.setName("closeButton"); // NOI18N
        closeButton.setOpaque(false);
        closeButton.setBounds(330, 280, 73, 23);
        layeredPane.add(closeButton, javax.swing.JLayeredPane.PALETTE_LAYER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, 416, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(layeredPane, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    @Action
    public void closeAboutBox() {
        setVisible(false);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel appDescLabel;
    private javax.swing.JLabel appHomePageLabel;
    private javax.swing.JLabel appVendorLabel;
    private javax.swing.JLabel appVersionLabel;
    private javax.swing.JButton closeButton;
    private javax.swing.JLabel homePageLabel;
    private javax.swing.JLayeredPane layeredPane;
    private javax.swing.JLabel logo;
    private javax.swing.JLabel vendorLabel;
    private javax.swing.JLabel versionLabel;
    // End of variables declaration//GEN-END:variables
    
}
